---

# Targeting specific OSes or distributions:
#
#   - `ansible_system`               → Linux, BSD, ...
#   - `ansible_os_family`            → Debian, RedHat, ...
#   - `ansible_distribution`         → Debian, Ubuntu, RedHat, ...
#   - `ansible_distribution_release` → precise, wheezy, ...
#   - `ansible_pkg_mgr`              → apt, yum, ...

- name: Install pip
  become: yes
  become_method: sudo
  yum: name=python27-pip state=present

- name: Link /usr/bin/pip-2.7 to /usr/bin/pip
  become: yes
  become_user: root
  file: src=/usr/bin/pip-2.7 dest=/usr/bin/pip state=link

- name: Install Supervisord
  become: yes
  become_user: root
  when: ansible_os_family == "RedHat"
  pip: name=supervisor
  tags:
    - init
    - supervisor
    - supervisord
  register: sp

- debug: msg="{{sp}}"
