---

# Targeting specific OSes or distributions:
#
#   - `ansible_system`               → Linux, BSD, ...
#   - `ansible_os_family`            → Debian, RedHat, ...
#   - `ansible_distribution`         → Debian, Ubuntu, RedHat, ...
#   - `ansible_distribution_release` → precise, wheezy, ...
#   - `ansible_pkg_mgr`              → apt, yum, ...

- name: Install Supervisord
  become: yes
  become_user: root
  when: ansible_os_family == "RedHat"
  command: pip install supervisor
  tags:
    - init
    - supervisor
    - supervisord
