---

# Delegate further configuration to subtasks
# placed in this same directory.

- include: "{{item}}"
  with_first_found:
    - files:
        - "install.{{ansible_distribution}}-{{ansible_distribution_release}}.yml"
        - "install.{{ansible_distribution}}.yml"
        - "install.{{ansible_os_family}}.yml"

- include: configure.yml

- name: Add supervisor group
  become: yes
  become_user: root
  group: name={{supervisor_group}} state=present

- name: Ensure supervisord is running
  sudo: yes
  service:
    name: "{{supervisord_service_name}}"
    state: running
    enabled: yes
  tags:
    - init
    - supervisor
    - supervisord
