---

- name: restart supervisord
  sudo: yes
  service: name={{supervisord_service_name}} state=restarted

- name: reread supervisord
  sudo: yes
  command: supervisorctl reread

- name: update supervisord
  sudo: yes
  command: supervisorctl update
