---

- name: restart supervisord
  become: yes
  become_user: root
  service: name={{supervisord_service_name}} state=restarted

- name: reread supervisord
  command: supervisorctl reread

- name: update supervisord
  command: supervisorctl update
